{{- if not .Values.appConfigFromSecret }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casibase-helm-chart.fullname" . }}-config
  labels:
    {{- include "casibase-helm-chart.labels" . | nindent 4 }}
data:
  app.conf: |
    {{- tpl .Values.appConfig . | nindent 4 }}
{{- end }}