{{- if and .Values.appConfigFromSecret .Values.appConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appConfigFromSecret }}
  labels:
    {{- include "casibase-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  app.conf: {{ tpl .Values.appConfig . | b64enc | quote }}
{{- end }}
